### ISSUE TITLE
the definition of reward

### ISSUE THREAD

**Issue by wweichn** [TuringsEgo/StarCraftAI#1]
Hi, I'm really curious about the definition of the reward. Do you have any basis or evidence?

**Comment by TuringsEgo** [comment]
This is designed to be a framework for a model based approach to the game. Different aspects of the game will have different models operating. The end result is that one will be able to train them separately and then be able to train a better model and be able to seemlessly plug it into the framework to interact with the rest of the models.

That being said, different models should be expecting different rewards. For a macro model, it would probably make sense for episodic learning with win +1 and loss -1. For a micro model, the reward would be the sum of your units health - the sum of the enemy units health

**Comment by wweichn** [comment]
Yeah, I use the the sum of my units health - the sum of the enemy units health as reward, and it doesn't work well. Because the reward appeared to be 0 multiple times during a battle, maybe it's because all attack actions must continue for a while to hurt enemy? I don't know whether its the reason to make my training get bad result

**Comment by TuringsEgo** [comment]
Are you not incorporating latency frames? Facebook let every action execute for 9 frames before selecting another action.

**Comment by wweichn** [comment]
No, I set frame skip as 9 frames.

**Comment by TuringsEgo** [comment]
Hm. I'm not sure then. Is your code on github?
